Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    config.vm.provider "hyperv" do |h|
        h.enable_virtualization_extensions = true
        h.differencing_disk = true
        end
end